# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - asciiman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false # Prevent treating warnings as errors
          NODE_ENV: production

      - name: Prepare deployment package
        run: |
          mkdir deployment
          cp -r dist/ deployment/
          cp -r dist-server/ deployment/
          cp package.json deployment/
          cp package-lock.json deployment/
          cp web.config deployment/
          cp .deployment deployment/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CC54C1E9B63B46F9BB0AA7B48EC77C7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_30CCA3CC3A6643A6816E9C528DA8D515 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_70E23BD1D7824868AB664E9F2FCB4D1C }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'asciiman'
          slot-name: 'Production'
          package: .

      - name: 'Configure startup command'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'asciiman'
          app-settings-json: |
            [
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "0",
                "slotSetting": false
              },
              {
                "name": "NODE_ENV",
                "value": "production",
                "slotSetting": false
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "18.x",
                "slotSetting": false
              },
              {
                "name": "WEBSITE_NPM_DEFAULT_VERSION",
                "value": "10.2.4",
                "slotSetting": false
              }
            ]
          mask-inputs: false

      - name: 'Start application'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'asciiman'
          slot-name: 'Production'
          startup-command: 'cd /home/site/wwwroot && npm ci --only=production && npm start'
          